name: XConn CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Install dependencies
        run: make setup

      - name: Run lint
        run: make check-lint

      - name: Build project
        run: make build

      - name: Setup AAT
        run: |
          git clone https://github.com/xconnio/xconn-aat-setup.git
          cd xconn-aat-setup
          make build-docker-xconn
          docker compose up -d
          timeout 30 bash -c 'until nc -z localhost 8080 && nc -z localhost 8081; do sleep 1; done'
